name: backend-ci

on:
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

defaults:
  run:
    shell: bash
    working-directory: backend

jobs:

  tests:
    name: Application tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test with Maven
        run: ./mvnw test
