name: backend-ci

on:
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

jobs:

  tests:
    name: Application tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test with Maven
        working-directory: backend
        run: ./mvnw test
  
  deploy:
    name: Deploy
    needs: tests
    env:
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure SSH
        run: |
          mkdir ~/.ssh
          echo "$known_hosts" > ~/.ssh/known_hosts
          echo "$private_key" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - run: scp -r backend backend@13.69.249.213:~/
      - run: ssh backend@13.69.249.213 mvn -f ./backend spring-boot:run
